### ISSUE TITLE
Routines are stopped too early

### ISSUE THREAD

**Issue by Inspyro** [tomblind/unity-async-routines#3]
Example code:
```
using System;
using AsyncRoutines;
using UnityEngine;

public class RoutineBug : MonoBehaviour
{
    public RoutineManagerBehavior routineManager;
    
    public void Start()
    {
        routineManager.Run(StartCountdown());
    }

    public async Routine StartCountdown()
    {
        var countDown = Countdown();
        await Routine.WaitForSeconds(2f);

        if (countDown.IsDead)
            throw new InvalidOperationException("This shoud not happen");
        
        routineManager.Run(countDown);
    }

    public async Routine Countdown()
    {
        for (var i = 10; i >= 0; --i)
        {
            Debug.Log(i);
            await Routine.WaitForSeconds(1);
        }
    }
}
```

When storing a Routine in a variable (same as what would work with normal async Tasks) and calling another routine in between such as WaitForSeconds the previous routines are **stopped before they finished running**.

Of course this is a rather trivial example, but in real-life use cases there are many bugs that can be caused by this behaviour

**Comment by tomblind** [comment]
Thanks for reporting this. I have a fix for the issue in the branch [bugfix/child-premature-stop](https://github.com/tomblind/unity-async-routines/tree/bugfix/child-premature-stop). Once I've had a chance to test it thoroughly, I'll merge into master.
